### PR TITLE
Variant groups

### PR DESCRIPTION
**Pull request by kronenthaler**
Attempt to solve #113. Needs confirmation from @st3fan.
How to use:

```
# load project as usual
project.add_file('en.lproj/<file1>.strings', ...)
project.add_file('en.lproj/<file2>.strings', ...)
project.add_file('en.lproj/<file3>.strings', ...)
```

Maybe i will add a helper method to add a full folder later on, after confirm that this works as expected.

### CODE REVIEW

**Comment by eAi** [comment]
I've created a pull request that fixes some issues with this: https://github.com/kronenthaler/mod-pbxproj/pull/124 (I apologies if I've done this incorrectly, I'm a bit of a GitHub newb!)

**Comment by st3fan** [comment]
Sorry for not responding, I will try to give this a go next week.

**Comment by MacAccount** [comment]
I'm trying to do the same thing as st3fan here. I have a bunch of InfoPlist.strings in different language_code.lprof folders where language_code can be de, fr etc and I want to add them to my project. I have tried the following:

`from pbxproj import XcodeProject
project = XcodeProject.load('./myProject.xcodeproj/project.pbxproj')`

`project.add_file('./de.lproj/InfoPlist.strings', force=False)`

`project.save()`

However, after executing the above the InfoPlist.strings file was not added. Using diff shows no changes were made to the project.pbxproj file.

If I instead set force=True in the add_file function then I get the following error:

`Traceback (most recent call last):`

  `File "import.py", line 4, in <module>`
    `project.add_file('./de.lproj/InfoPlist.strings', force=True, parent='InfoPlist.strings')`
  `File "/Library/Python/2.7/site-packages/pbxproj/pbxextensions/ProjectFiles.py", line 123, in add_file`
    `file_options)`
  `File "/Library/Python/2.7/site-packages/pbxproj/pbxextensions/ProjectFiles.py", line 395, in _add_file_reference`
    `self._get_parent_group(parent).add_child(file_ref)`
`AttributeError: 'NoneType' object has no attribute 'add_child'`

**Comment by kronenthaler** [comment]
This PR is very incomplete and buggy. It needs more work. I will close and reopen when better solution comes.

**Pull request closed without merging**
