### PR TITLE
Update ProjectFiles to support xcframeworks

### PR DESCRIPTION
**Pull request by masterrex**
Adding support for Apple-native xcframework file types

### CODE REVIEW

**Comment by masterrex** [comment]
Looks like the checks are failing for an unrelated reason: `coveralls.exception.CoverallsException: Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.`

**Comment by kronenthaler** [comment]
> Looks like the checks are failing for an unrelated reason:
> 
> ```
> coveralls.exception.CoverallsException: Running on Github Actions but GITHUB_TOKEN is not set. Add "env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}" to your step config.
> ```

Yes, i have addressed in the master branch now

**Comment by kronenthaler** [comment]
Thanks for your contribution. 

All looking good. One last request, could you add a small unit test for it?

**Comment by masterrex** [comment]
@kronenthaler I have pulled from master, added a unit test and pushed updates the PR, looks like the checks worked for 3.6 but not the other versions.

**Comment by masterrex** [comment]
@kronenthaler  is it possible to release a 3.2.1 patch version with these changes? I am actively working on a project that needs to consume these itty bitty details. Thank you!

**Comment by kronenthaler** [comment]
Release on its way

**Pull request merged**
